### ISSUE TITLE
Dispose with an active Ticker

### ISSUE THREAD

**Issue by pulstar** [tranhuycong/custom_splash#4]
**Sometimes I got the error below while using the hot restart...**

The following assertion was thrown while finalizing the widget tree:
_CustomSplashState#94221(ticker active) was disposed with an active Ticker.

_CustomSplashState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: Ticker(created by _CustomSplashState#94221(lifecycle state: created))
The stack trace when the Ticker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:66:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:68:6)
#2      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:95:15)
#3      new AnimationController (package:flutter/src/animation/animation_controller.dart:245:21)
#4      _CustomSplashState.initState (package:custom_splash/custom_splash.dart:58:32)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#82     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#94     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#104    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#107    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:591:16)
#108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#123    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#128    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#129    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#133    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#136    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#179    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#184    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#191    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#192    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#193    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#203    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#209    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#225    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#230    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#231    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#232    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#233    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#234    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#235    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#239    _invoke (dart:ui/hooks.dart:259:10)
#240    _drawFrame (dart:ui/hooks.dart:217:3)
(elided 3 frames from package dart:async)

When the exception was thrown, this was the stack: 
#0      SingleTickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:108:7)
#1      SingleTickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:122:6)
#2      _CustomSplashState.dispose (package:custom_splash/custom_splash.dart:67:11)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
...

**Comment by khalifa007** [comment]
m2
