### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by CedYF** [tranhuycong/custom_splash#5]
Any solutions for this?

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3763:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3777:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3896:12)
#3      Navigator.of (package:flutter/src/widgets/navigator.dart:1620:19)
#4      _CustomSplashState.build.<anonymous closure>.<anonymous closure> (package:custom_splash/custom_splash.dart:117:25)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)

**Comment by khalifa007** [comment]
mee too

**Comment by pulstar** [comment]
This problem became worse with the last Flutter version (1.17.0). It appears sometimes before, now it shows up almost everytime.

```
E/flutter ( 7399): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter ( 7399): At this point the state of the widget's element tree is no longer stable.
E/flutter ( 7399): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter ( 7399): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
E/flutter ( 7399): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
E/flutter ( 7399): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
E/flutter ( 7399): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
E/flutter ( 7399): #4      _CustomSplashState.build.<anonymous closure> (package:custom_splash/custom_splash.dart:122:23)
E/flutter ( 7399): #5      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7399): #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7399): #7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 7399): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 7399): #9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 7399): #10     Future._complete (dart:async/future_impl.dart:516:7)
E/flutter ( 7399): #11     new Future.delayed.<anonymous closure> (dart:async/future.dart:315:16)
E/flutter ( 7399): #12     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 7399): #13     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7399): #14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 7399): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 7399): #16     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 7399): #17     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7399): #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 7399): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7399): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7399): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7399): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by yazici75** [comment]
any solution ?

**Comment by pulstar** [comment]
After many tries I give up and now I am using a Flutter native solution.

**Comment by yazici75** [comment]
The problem is Future.delayed function in widget build. Because Everytime widget builds, future.delayed runs. Even if route changes, Future.delayed attempts to navigate replacement to new route. But old route has already gone. Solution is using Future.delayed function in init state.

**Comment by thiago-molive** [comment]
the solution is change the customFunction to async and remove Future.delayed.
